2024-11-07 13:17:28,345 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:17:28,345 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:17:28,349 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:17:28,350 - reloader - INFO -  * Detected change in 'C:\\Users\\JosephThurlow\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\idna.py', reloading
2024-11-07 13:17:30,138 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:17:30,138 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:17:30,140 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:17:32,179 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 13:17:32,179 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:17:32,233 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:17:34,298 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:17:34,299 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:17:54,508 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:17:56,544 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 400 68
2024-11-07 13:17:56,544 - SeaingAPIClient - ERROR - /image/enhance - 400 - {'error': 'Session ID is required for WebSocket communication'}
2024-11-07 13:17:56,544 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 96, in enhanceImage
    self.client.upload(img_bytes)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 77, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 13:20:03,073 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\datastructures\\structures.py', reloading
2024-11-07 13:28:12,177 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:28:12,177 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:28:12,179 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:28:14,209 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 13:28:14,209 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:28:14,233 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:28:16,250 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:28:16,251 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:28:20,598 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:28:21,526 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 13:28:22,635 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:28:22,636 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:28:23,575 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 13:28:23,575 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 13:28:23,575 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 13:29:06,700 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 13:29:06,700 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 13:29:06,701 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 13:29:06,701 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 13:29:11,812 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:29:11,812 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:29:11,814 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:29:13,835 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 13:29:13,836 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:29:13,858 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:29:15,878 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:29:15,878 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:29:18,238 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:29:20,280 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 13:29:20,280 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 13:29:20,280 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 13:31:00,637 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:31:00,637 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:31:00,640 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:31:02,666 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 13:31:02,667 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:31:02,668 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:31:04,707 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 13:31:04,708 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:31:17,515 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaingclearly\\iot\\service.py', reloading
2024-11-07 13:31:17,515 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaingclearly\\iot\\service.py', reloading
2024-11-07 13:31:17,515 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaingclearly\\iot\\service.py', reloading
2024-11-07 13:31:23,196 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:31:23,196 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:31:23,198 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:31:25,235 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 13:31:25,235 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:31:25,236 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:31:27,295 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 13:31:27,296 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:32:55,912 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:32:55,912 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:32:55,915 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:32:57,951 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 13:32:57,952 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:32:57,953 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:32:59,994 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 13:32:59,994 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:32:59,995 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:33:02,047 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 13:33:02,047 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:33:02,069 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\matcher.py', reloading
2024-11-07 13:33:02,076 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:33:02,077 - SeaingService - ERROR - WebSocket error: Handshake status 500 INTERNAL SERVER ERROR -+-+- {'server': 'Werkzeug/3.0.4 Python/3.12.1', 'date': 'Thu, 07 Nov 2024 03:33:02 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '7596', 'connection': 'close'} -+-+- b'<!doctype html>\n<html lang=en>\n  <head>\n    <title>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script>\n      var CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = "IFy8PLBfAjixOwcMTW0h";\n    </script>\n  </head>\n  <body style="background-color: #fff">\n    <div class="debugger">\n<h1>WebsocketMismatch</h1>\n<div class="detail">\n  <p class="errormsg">werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  <h3></h3>\n  <ul><li><div class="frame" id="frame-2260406236736">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1498</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>\n<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>\n<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>\n<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)\n<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2260406237024">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py"</cite>,\n      line <em class="line">40</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>self.wsgi_app = wsgi_app</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>\n<pre class="line before"><span class="ws">        </span>adapter = self.ws.url_map.bind_to_environ(environ)</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line current"><span class="ws">            </span>handler, values = adapter.match()\n<span class="ws">            </span>                  ^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws">            </span>environment = environ[&#39;wsgi.websocket&#39;]</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>with self.app.app_context():</pre>\n<pre class="line after"><span class="ws">                </span>with self.app.request_context(environ):</pre>\n<pre class="line after"><span class="ws">                    </span>handler(environment, **values)</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2260406237168">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py"</cite>,\n      line <em class="line">627</em>,\n      in <code class="function">match</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>except NoMatch as e:</pre>\n<pre class="line before"><span class="ws">            </span>if e.have_match_for:</pre>\n<pre class="line before"><span class="ws">                </span>raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">            </span>if e.websocket_mismatch:</pre>\n<pre class="line current"><span class="ws">                </span>raise WebsocketMismatch() from None\n<span class="ws">                </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>raise NotFound() from None</pre>\n<pre class="line after"><span class="ws">        </span>else:</pre>\n<pre class="line after"><span class="ws">            </span>rule, rv = result</pre>\n<pre class="line after"><span class="ws"></span> </pre></div>\n</div>\n</ul>\n  <blockquote>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</blockquote>\n</div>\n\n<div class="plain">\n    <p>\n      This is the Copy/Paste friendly version of the traceback.\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py&#34;, line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py&#34;, line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py&#34;, line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</textarea>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n\n    <div class="pin-prompt">\n      <div class="inner">\n        <h3>Console Locked</h3>\n        <p>\n          The console is locked and needs to be unlocked by entering the PIN.\n          You can find the PIN printed out on the standard output of your\n          shell that runs the server.\n        <form>\n          <p>PIN:\n            <input type=text name=pin size=14>\n            <input type=submit name=btn value="Confirm Pin">\n        </form>\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py", line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py", line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py", line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n\n\n-->\n'
2024-11-07 13:33:02,085 - websocket - ERROR - Handshake status 500 INTERNAL SERVER ERROR -+-+- {'server': 'Werkzeug/3.0.4 Python/3.12.1', 'date': 'Thu, 07 Nov 2024 03:33:02 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '7596', 'connection': 'close'} -+-+- b'<!doctype html>\n<html lang=en>\n  <head>\n    <title>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script>\n      var CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = "IFy8PLBfAjixOwcMTW0h";\n    </script>\n  </head>\n  <body style="background-color: #fff">\n    <div class="debugger">\n<h1>WebsocketMismatch</h1>\n<div class="detail">\n  <p class="errormsg">werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  <h3></h3>\n  <ul><li><div class="frame" id="frame-2260406236736">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1498</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>\n<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>\n<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>\n<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)\n<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2260406237024">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py"</cite>,\n      line <em class="line">40</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>self.wsgi_app = wsgi_app</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>\n<pre class="line before"><span class="ws">        </span>adapter = self.ws.url_map.bind_to_environ(environ)</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line current"><span class="ws">            </span>handler, values = adapter.match()\n<span class="ws">            </span>                  ^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws">            </span>environment = environ[&#39;wsgi.websocket&#39;]</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>with self.app.app_context():</pre>\n<pre class="line after"><span class="ws">                </span>with self.app.request_context(environ):</pre>\n<pre class="line after"><span class="ws">                    </span>handler(environment, **values)</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2260406237168">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py"</cite>,\n      line <em class="line">627</em>,\n      in <code class="function">match</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>except NoMatch as e:</pre>\n<pre class="line before"><span class="ws">            </span>if e.have_match_for:</pre>\n<pre class="line before"><span class="ws">                </span>raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">            </span>if e.websocket_mismatch:</pre>\n<pre class="line current"><span class="ws">                </span>raise WebsocketMismatch() from None\n<span class="ws">                </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>raise NotFound() from None</pre>\n<pre class="line after"><span class="ws">        </span>else:</pre>\n<pre class="line after"><span class="ws">            </span>rule, rv = result</pre>\n<pre class="line after"><span class="ws"></span> </pre></div>\n</div>\n</ul>\n  <blockquote>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</blockquote>\n</div>\n\n<div class="plain">\n    <p>\n      This is the Copy/Paste friendly version of the traceback.\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py&#34;, line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py&#34;, line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py&#34;, line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</textarea>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n\n    <div class="pin-prompt">\n      <div class="inner">\n        <h3>Console Locked</h3>\n        <p>\n          The console is locked and needs to be unlocked by entering the PIN.\n          You can find the PIN printed out on the standard output of your\n          shell that runs the server.\n        <form>\n          <p>PIN:\n            <input type=text name=pin size=14>\n            <input type=submit name=btn value="Confirm Pin">\n        </form>\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py", line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py", line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py", line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n\n\n-->\n' - goodbye
2024-11-07 13:33:02,086 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:33:04,114 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:33:04,115 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:33:24,119 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:33:24,119 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:33:24,121 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:33:26,184 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 13:33:26,184 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:33:26,185 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:33:28,246 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 13:33:28,246 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:33:28,248 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:33:30,288 - SeaingService - ERROR - WebSocket error: Handshake status 500 INTERNAL SERVER ERROR -+-+- {'server': 'Werkzeug/3.0.4 Python/3.12.1', 'date': 'Thu, 07 Nov 2024 03:33:30 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '7596', 'connection': 'close'} -+-+- b'<!doctype html>\n<html lang=en>\n  <head>\n    <title>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script>\n      var CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = "QyB3ZOI9kUzioHbbYYfm";\n    </script>\n  </head>\n  <body style="background-color: #fff">\n    <div class="debugger">\n<h1>WebsocketMismatch</h1>\n<div class="detail">\n  <p class="errormsg">werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  <h3></h3>\n  <ul><li><div class="frame" id="frame-2302114722672">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1498</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>\n<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>\n<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>\n<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)\n<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2302114722816">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py"</cite>,\n      line <em class="line">40</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>self.wsgi_app = wsgi_app</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>\n<pre class="line before"><span class="ws">        </span>adapter = self.ws.url_map.bind_to_environ(environ)</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line current"><span class="ws">            </span>handler, values = adapter.match()\n<span class="ws">            </span>                  ^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws">            </span>environment = environ[&#39;wsgi.websocket&#39;]</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>with self.app.app_context():</pre>\n<pre class="line after"><span class="ws">                </span>with self.app.request_context(environ):</pre>\n<pre class="line after"><span class="ws">                    </span>handler(environment, **values)</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2302114723824">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py"</cite>,\n      line <em class="line">627</em>,\n      in <code class="function">match</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>except NoMatch as e:</pre>\n<pre class="line before"><span class="ws">            </span>if e.have_match_for:</pre>\n<pre class="line before"><span class="ws">                </span>raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">            </span>if e.websocket_mismatch:</pre>\n<pre class="line current"><span class="ws">                </span>raise WebsocketMismatch() from None\n<span class="ws">                </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>raise NotFound() from None</pre>\n<pre class="line after"><span class="ws">        </span>else:</pre>\n<pre class="line after"><span class="ws">            </span>rule, rv = result</pre>\n<pre class="line after"><span class="ws"></span> </pre></div>\n</div>\n</ul>\n  <blockquote>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</blockquote>\n</div>\n\n<div class="plain">\n    <p>\n      This is the Copy/Paste friendly version of the traceback.\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py&#34;, line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py&#34;, line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py&#34;, line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</textarea>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n\n    <div class="pin-prompt">\n      <div class="inner">\n        <h3>Console Locked</h3>\n        <p>\n          The console is locked and needs to be unlocked by entering the PIN.\n          You can find the PIN printed out on the standard output of your\n          shell that runs the server.\n        <form>\n          <p>PIN:\n            <input type=text name=pin size=14>\n            <input type=submit name=btn value="Confirm Pin">\n        </form>\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py", line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py", line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py", line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n\n\n-->\n'
2024-11-07 13:33:30,288 - websocket - ERROR - Handshake status 500 INTERNAL SERVER ERROR -+-+- {'server': 'Werkzeug/3.0.4 Python/3.12.1', 'date': 'Thu, 07 Nov 2024 03:33:30 GMT', 'content-type': 'text/html; charset=utf-8', 'content-length': '7596', 'connection': 'close'} -+-+- b'<!doctype html>\n<html lang=en>\n  <head>\n    <title>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css">\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script>\n      var CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = "QyB3ZOI9kUzioHbbYYfm";\n    </script>\n  </head>\n  <body style="background-color: #fff">\n    <div class="debugger">\n<h1>WebsocketMismatch</h1>\n<div class="detail">\n  <p class="errormsg">werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  <h3></h3>\n  <ul><li><div class="frame" id="frame-2302114722672">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1498</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">    </span>) -&gt; cabc.Iterable[bytes]:</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;The WSGI server calls the Flask application object as the</pre>\n<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre>\n<pre class="line before"><span class="ws">        </span>wrapped to apply middleware.</pre>\n<pre class="line before"><span class="ws">        </span>&#34;&#34;&#34;</pre>\n<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)\n<span class="ws">        </span>       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2302114722816">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py"</cite>,\n      line <em class="line">40</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>self.wsgi_app = wsgi_app</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>\n<pre class="line before"><span class="ws">        </span>adapter = self.ws.url_map.bind_to_environ(environ)</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line current"><span class="ws">            </span>handler, values = adapter.match()\n<span class="ws">            </span>                  ^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws">            </span>environment = environ[&#39;wsgi.websocket&#39;]</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>with self.app.app_context():</pre>\n<pre class="line after"><span class="ws">                </span>with self.app.request_context(environ):</pre>\n<pre class="line after"><span class="ws">                    </span>handler(environment, **values)</pre></div>\n</div>\n\n<li><div class="frame" id="frame-2302114723824">\n  <h4>File <cite class="filename">"D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py"</cite>,\n      line <em class="line">627</em>,\n      in <code class="function">match</code></h4>\n  <div class="source "><pre class="line before"><span class="ws">        </span>except NoMatch as e:</pre>\n<pre class="line before"><span class="ws">            </span>if e.have_match_for:</pre>\n<pre class="line before"><span class="ws">                </span>raise MethodNotAllowed(valid_methods=list(e.have_match_for)) from None</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">            </span>if e.websocket_mismatch:</pre>\n<pre class="line current"><span class="ws">                </span>raise WebsocketMismatch() from None\n<span class="ws">                </span>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">            </span>raise NotFound() from None</pre>\n<pre class="line after"><span class="ws">        </span>else:</pre>\n<pre class="line after"><span class="ws">            </span>rule, rv = result</pre>\n<pre class="line after"><span class="ws"></span> </pre></div>\n</div>\n</ul>\n  <blockquote>werkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</blockquote>\n</div>\n\n<div class="plain">\n    <p>\n      This is the Copy/Paste friendly version of the traceback.\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py&#34;, line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py&#34;, line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File &#34;D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py&#34;, line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n</textarea>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n\n    <div class="pin-prompt">\n      <div class="inner">\n        <h3>Console Locked</h3>\n        <p>\n          The console is locked and needs to be unlocked by entering the PIN.\n          You can find the PIN printed out on the standard output of your\n          shell that runs the server.\n        <form>\n          <p>PIN:\n            <input type=text name=pin size=14>\n            <input type=submit name=btn value="Confirm Pin">\n        </form>\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\app.py", line 1498, in __call__\n    return self.wsgi_app(environ, start_response)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_sockets.py", line 40, in __call__\n    handler, values = adapter.match()\n                      ^^^^^^^^^^^^^^^\n  File "D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\routing\\map.py", line 627, in match\n    raise WebsocketMismatch() from None\nwerkzeug.routing.exceptions.WebsocketMismatch: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.\n\n\n-->\n' - goodbye
2024-11-07 13:33:30,289 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:33:30,291 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 13:33:30,291 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:33:30,311 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 13:33:32,356 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 13:33:32,356 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:34:57,772 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask_session\\__init__.py', reloading
2024-11-07 13:34:57,828 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\typing.py', reloading
2024-11-07 13:34:57,829 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\sansio\\response.py', reloading
2024-11-07 13:34:57,836 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\werkzeug\\datastructures\\__init__.py', reloading
2024-11-07 13:36:58,131 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:36:58,131 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:36:58,133 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:37:18,289 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:37:18,289 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:37:18,291 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:37:20,330 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 13:37:20,331 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:37:20,341 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 13:37:20,341 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:37:20,348 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 13:37:20,349 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:37:20,381 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:37:20,381 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:37:22,365 - SeaingService - ERROR - WebSocket error: Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:37:22 GMT'} -+-+- b'Internal Server Error'
2024-11-07 13:37:22,365 - websocket - ERROR - Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:37:22 GMT'} -+-+- b'Internal Server Error' - goodbye
2024-11-07 13:37:22,365 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:41:23,580 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:41:23,580 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:41:23,582 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:41:25,625 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 13:41:25,626 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:41:25,636 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 13:41:25,637 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:41:25,644 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 13:41:25,645 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:41:25,675 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:41:25,676 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:41:27,692 - SeaingService - ERROR - WebSocket error: Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:41:27 GMT'} -+-+- b'Internal Server Error'
2024-11-07 13:41:27,692 - websocket - ERROR - Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:41:27 GMT'} -+-+- b'Internal Server Error' - goodbye
2024-11-07 13:41:27,692 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:41:34,951 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 33
2024-11-07 13:41:34,952 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 13:41:34,952 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 13:44:06,112 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:44:06,112 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:44:06,114 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:44:08,159 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 13:44:08,160 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:44:08,169 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 13:44:08,170 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:44:08,178 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 13:44:08,178 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:44:08,207 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:44:08,208 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:44:10,204 - SeaingService - ERROR - WebSocket error: Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:44:10 GMT'} -+-+- b'Internal Server Error'
2024-11-07 13:44:10,204 - websocket - ERROR - Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:44:10 GMT'} -+-+- b'Internal Server Error' - goodbye
2024-11-07 13:44:10,205 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:44:16,866 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\config.py', reloading
2024-11-07 13:44:56,759 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:44:56,759 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:44:56,764 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:44:58,820 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 13:44:58,821 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:44:58,830 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 13:44:58,831 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:44:58,838 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 13:44:58,839 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:44:58,868 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:44:58,868 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:45:00,872 - SeaingService - ERROR - WebSocket error: Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:45:00 GMT'} -+-+- b'Internal Server Error'
2024-11-07 13:45:00,872 - websocket - ERROR - Handshake status 500 Internal Server Error -+-+- {'content-type': 'text/plain', 'connection': 'close', 'content-length': '21', 'date': 'Thu, 07 Nov 2024 03:45:00 GMT'} -+-+- b'Internal Server Error' - goodbye
2024-11-07 13:45:00,872 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:45:12,022 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\gevent\\_ffi\\loop.py', reloading
2024-11-07 13:45:12,023 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\gevent\\baseserver.py', reloading
2024-11-07 13:58:10,887 - SeaingService - INFO - Starting Seaing Service
2024-11-07 13:58:10,887 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 13:58:10,890 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 13:58:10,896 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 13:58:10,896 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 13:58:10,906 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 13:58:10,907 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 13:58:10,914 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 13:58:10,915 - SeaingAPIClient - INFO - /options - 200
2024-11-07 13:58:10,934 - SeaingService - ERROR - WebSocket error: Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 03:58:10 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n'
2024-11-07 13:58:10,934 - websocket - ERROR - Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 03:58:10 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n' - goodbye
2024-11-07 13:58:10,935 - SeaingService - INFO - WebSocket connection closed
2024-11-07 13:58:10,945 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:10,946 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:16,807 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:16,808 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:17,550 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:17,551 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:19,902 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:19,902 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:21,385 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:21,385 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:21,844 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:21,844 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:22,483 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 13:58:22,484 - SeaingAPIClient - INFO - /config - 200
2024-11-07 13:58:24,246 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 33
2024-11-07 13:58:24,247 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 13:58:24,247 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 13:58:32,362 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 33
2024-11-07 13:58:32,363 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 13:58:32,363 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:01:37,412 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:01:37,412 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:01:37,413 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:01:42,789 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:01:42,789 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:01:42,791 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:01:42,796 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\gevent\\libuv\\loop.py', reloading
2024-11-07 14:01:42,798 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 14:01:42,798 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:01:42,809 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 14:01:42,810 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:01:42,818 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 14:01:42,818 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:01:42,835 - SeaingService - ERROR - WebSocket error: Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 04:01:42 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n'
2024-11-07 14:01:42,836 - websocket - ERROR - Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 04:01:42 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n' - goodbye
2024-11-07 14:01:42,836 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:01:42,847 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 14:01:42,848 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:01:54,236 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:01:54,236 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:01:54,238 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:01:54,244 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 49
2024-11-07 14:01:54,244 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:01:54,254 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 40
2024-11-07 14:01:54,255 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:01:54,262 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 989
2024-11-07 14:01:54,263 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:01:54,281 - SeaingService - ERROR - WebSocket error: Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 04:01:54 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n'
2024-11-07 14:01:54,281 - websocket - ERROR - Handshake status 404 NOT FOUND -+-+- {'content-type': 'application/json', 'content-length': '81', 'date': 'Thu, 07 Nov 2024 04:01:54 GMT'} -+-+- b'{"error":"Not Found","message":"The requested URL was not found on the server."}\n' - goodbye
2024-11-07 14:01:54,281 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:01:54,293 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 32
2024-11-07 14:01:54,293 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:02:01,167 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\cv2\\typing\\__init__.py', reloading
2024-11-07 14:02:01,169 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\cv2\\mat_wrapper\\__init__.py', reloading
2024-11-07 14:17:43,195 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:17:43,195 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:17:43,199 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:17:43,200 - reloader - INFO -  * Detected change in 'C:\\Users\\JosephThurlow\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\idna.py', reloading
2024-11-07 14:17:44,995 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:17:44,996 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:17:44,998 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:17:47,056 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:17:47,057 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:17:47,057 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:17:49,108 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:17:49,109 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:17:49,109 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:17:51,147 - websocket - INFO - Websocket connected
2024-11-07 14:17:51,147 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:17:51,147 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:17:51,151 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:17:51,152 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:17:51,175 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:17:53,209 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:17:53,210 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:17:55,532 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:17:56,280 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:17:57,081 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): localhost:5000
2024-11-07 14:17:57,445 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (4): localhost:5000
2024-11-07 14:17:57,590 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:17:57,590 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:17:58,301 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:17:58,334 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:17:58,334 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:17:59,121 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:17:59,121 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:17:59,477 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:17:59,478 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:18:00,340 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:18:00,340 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:18:00,340 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:18:29,584 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:18:29,591 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:18:29,591 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:18:50,700 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:18:50,701 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:18:50,703 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:18:52,749 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:18:52,750 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:18:52,751 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:18:54,798 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:18:54,798 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:18:54,799 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:18:56,834 - websocket - INFO - Websocket connected
2024-11-07 14:18:56,834 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:18:56,835 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:18:56,839 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:18:56,839 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:18:56,860 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:18:58,908 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:18:58,908 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:19:03,634 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:19:04,142 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:19:04,957 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): localhost:5000
2024-11-07 14:19:05,402 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (4): localhost:5000
2024-11-07 14:19:05,669 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:19:05,670 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:19:06,046 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:19:06,184 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:19:06,185 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:19:07,005 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:19:07,006 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:19:07,450 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:19:07,451 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:19:08,092 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:19:08,092 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:19:08,092 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:19:57,384 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:19:57,385 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:19:57,385 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:20:10,116 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:20:10,117 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:20:10,119 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:20:12,156 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:20:12,157 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:20:12,157 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:14,195 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:20:14,196 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:20:14,197 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:16,235 - websocket - INFO - Websocket connected
2024-11-07 14:20:16,235 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:20:16,236 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:20:16,240 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:20:16,240 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:20:16,261 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:18,313 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:20:18,313 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:20:32,329 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:20:32,329 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:20:32,330 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:20:38,061 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:20:38,061 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:20:38,063 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:20:40,086 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:20:40,086 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:20:40,087 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:42,119 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:20:42,120 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:20:42,121 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:44,156 - websocket - INFO - Websocket connected
2024-11-07 14:20:44,156 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:20:44,156 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:20:44,162 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:20:44,162 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:20:44,182 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:20:46,230 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:20:46,230 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:21:03,015 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:21:03,016 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:21:03,016 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-07 14:21:10,809 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:21:10,809 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:21:10,811 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:21:12,845 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:21:12,846 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:21:12,846 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:21:14,895 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:21:14,896 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:21:14,897 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:21:16,931 - websocket - INFO - Websocket connected
2024-11-07 14:21:16,931 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:21:16,936 - SeaingService - ERROR - WebSocket error: rsv is not implemented, yet
2024-11-07 14:21:16,936 - websocket - ERROR - rsv is not implemented, yet - goodbye
2024-11-07 14:21:16,936 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:21:16,939 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:21:16,939 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:21:16,963 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:21:19,021 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:21:19,022 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:25,382 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:23:25,383 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:23:25,385 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:23:27,421 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:23:27,422 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:23:27,423 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:29,472 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:23:29,473 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:23:29,474 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:31,510 - websocket - INFO - Websocket connected
2024-11-07 14:23:31,510 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:23:31,515 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:23:31,515 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:23:31,535 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:33,569 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:33,569 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:36,480 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:36,892 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:23:37,487 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): localhost:5000
2024-11-07 14:23:37,904 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (4): localhost:5000
2024-11-07 14:23:38,523 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:38,524 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:38,944 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:38,945 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:39,533 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:39,534 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:39,934 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:39,935 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:41,971 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:44,011 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:23:44,012 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:23:44,012 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:23:46,594 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:48,654 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:23:48,654 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:23:48,654 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:23:52,388 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:53,355 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:54,437 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:54,438 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:55,403 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:23:55,403 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:23:55,938 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:23:57,990 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:23:57,990 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:23:57,990 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:24:04,194 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:05,591 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:06,245 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:24:06,246 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:24:07,632 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:24:07,632 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:24:07,632 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:24:20,902 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:22,921 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:24:22,921 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:24:26,066 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:28,107 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:24:28,108 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:24:28,108 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:24:34,154 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:36,196 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:24:36,196 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:24:36,196 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:24:45,982 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:48,016 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:24:48,017 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:24:48,017 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:24:56,464 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:24:58,529 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:24:58,529 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:24:58,529 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:34:41,410 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\skimage\\restoration\\deconvolution.py', reloading
2024-11-07 14:34:41,743 - SeaingService - ERROR - WebSocket error: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-07 14:34:41,743 - websocket - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host - goodbye
2024-11-07 14:34:41,744 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:34:49,842 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:34:49,842 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:34:49,844 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:34:51,899 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:34:51,899 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:34:51,900 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:34:53,951 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:34:53,952 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:34:53,953 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:34:55,982 - websocket - INFO - Websocket connected
2024-11-07 14:34:55,982 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:34:55,988 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:34:55,989 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:34:56,009 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:34:58,070 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:34:58,071 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:34:59,546 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:00,450 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:35:00,816 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (3): localhost:5000
2024-11-07 14:35:01,605 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:35:01,605 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:35:02,496 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:35:02,496 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:35:02,855 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:35:02,855 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:35:03,376 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:05,436 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:05,437 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:05,437 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:08,573 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:10,625 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:10,625 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:10,625 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:11,327 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:13,354 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:13,355 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:13,355 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:14,242 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:16,300 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:16,300 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:16,300 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:17,880 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:19,916 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:19,917 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:19,917 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:19,928 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:21,982 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:21,982 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:21,982 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:21,993 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:24,031 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:24,031 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:24,032 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:27,771 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:29,339 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:29,829 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:35:29,829 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:35:31,397 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:31,397 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:31,397 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:44,731 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:46,769 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:46,769 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:46,769 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:35:56,155 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:35:58,198 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:35:58,198 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:35:58,198 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:36:03,915 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:36:05,969 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:36:05,970 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:36:05,970 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:36:15,232 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:36:17,284 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:36:17,285 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:36:17,285 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:36:22,967 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:36:24,341 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:36:25,020 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:36:25,021 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:36:26,382 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:36:26,383 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:36:26,383 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:37:43,686 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:37:45,737 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:37:45,738 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:37:46,014 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:37:48,058 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:37:48,058 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:37:48,058 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:38:39,490 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:38:40,305 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:38:41,534 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:38:41,535 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:38:42,358 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:38:42,359 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:38:42,359 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:40:21,955 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:40:21,957 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:40:21,957 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:40:21,958 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:40:22,455 - SeaingService - ERROR - WebSocket error: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-07 14:40:22,455 - websocket - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host - goodbye
2024-11-07 14:40:22,455 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:40:28,759 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:40:28,759 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:40:28,761 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:40:30,812 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:40:30,813 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:40:30,814 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:40:32,864 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:40:32,865 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:40:32,866 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:40:34,906 - websocket - INFO - Websocket connected
2024-11-07 14:40:34,906 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:40:34,911 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:40:34,911 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:40:34,932 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:40:36,976 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:40:36,976 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:40:47,807 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:40:49,849 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:40:49,849 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:40:49,849 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:44:12,053 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:44:12,053 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:44:12,054 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:44:12,054 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:44:12,643 - SeaingService - ERROR - WebSocket error: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-07 14:44:12,643 - websocket - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host - goodbye
2024-11-07 14:44:12,643 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:44:17,713 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:44:17,713 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:44:17,715 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:44:19,771 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:44:19,772 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:44:19,772 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:44:21,827 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:44:21,828 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:44:21,829 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:44:23,868 - websocket - INFO - Websocket connected
2024-11-07 14:44:23,868 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:44:23,872 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:44:23,873 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:44:23,894 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:44:25,824 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:44:25,943 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:44:25,944 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:44:27,887 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:44:27,887 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:44:27,887 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:44:38,965 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:44:41,008 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:44:41,009 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:44:41,009 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:44:56,864 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:44:58,914 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:44:58,914 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:44:58,914 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:45:06,269 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:45:08,302 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:45:08,302 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:45:08,302 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:45:14,634 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:45:16,679 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:45:16,679 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:45:16,679 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:45:19,211 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:45:21,250 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:45:21,251 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:45:21,251 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:46:54,195 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:46:56,245 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:46:56,245 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:46:56,245 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:47:07,062 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\flask\\config.py', reloading
2024-11-07 14:47:07,069 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:47:07,070 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:47:07,072 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\processing.py', reloading
2024-11-07 14:47:07,406 - SeaingService - ERROR - WebSocket error: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-07 14:47:07,406 - websocket - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host - goodbye
2024-11-07 14:47:07,406 - SeaingService - INFO - WebSocket connection closed
2024-11-07 14:47:12,359 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:47:12,359 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:47:12,363 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:47:14,408 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:47:14,409 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:47:14,410 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:47:16,453 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:47:16,453 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:47:16,455 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:47:18,478 - websocket - INFO - Websocket connected
2024-11-07 14:47:18,478 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:47:18,498 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:47:18,499 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:47:18,520 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:47:20,554 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:47:20,554 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:47:25,208 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:47:27,268 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:47:27,268 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:47:27,268 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:49:03,698 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:49:03,698 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:49:03,700 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:49:05,764 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:49:05,765 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:49:05,766 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:49:07,809 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:49:07,809 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:49:07,810 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:49:09,846 - websocket - INFO - Websocket connected
2024-11-07 14:49:09,846 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:49:09,853 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:49:09,853 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:49:09,875 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:49:11,930 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:49:11,931 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:49:52,586 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:49:54,623 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:49:54,624 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:49:54,624 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:51:32,687 - SeaingService - INFO - Starting Seaing Service
2024-11-07 14:51:32,688 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 14:51:32,690 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 14:51:34,736 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 14:51:34,737 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 14:51:34,738 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:51:36,788 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 14:51:36,789 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 14:51:36,790 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:51:38,815 - websocket - INFO - Websocket connected
2024-11-07 14:51:38,815 - SeaingService - INFO - WebSocket connection opened
2024-11-07 14:51:38,838 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 14:51:38,838 - SeaingAPIClient - INFO - /options - 200
2024-11-07 14:51:38,862 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:51:40,900 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:51:40,901 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:51:57,852 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:51:59,886 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:51:59,886 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:51:59,887 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:52:02,070 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:52:04,117 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:52:04,118 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:52:04,118 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:52:05,300 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:52:07,352 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:52:07,352 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:52:07,352 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:52:09,961 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:52:12,018 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:52:12,019 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:52:12,019 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:52:14,835 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:52:16,877 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:52:16,877 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:52:16,878 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:12,165 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:14,220 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:14,220 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:14,220 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:17,214 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:18,189 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 14:54:19,249 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:54:19,250 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:54:20,243 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:20,244 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:20,244 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:20,626 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:22,670 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:22,670 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:22,670 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:24,600 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:26,650 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:26,650 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:26,650 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:27,438 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:29,490 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:29,491 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:29,491 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:30,435 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:32,493 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:32,493 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:32,493 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:53,079 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:55,128 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:54:55,129 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:54:55,129 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:54:58,304 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:54:59,468 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:55:00,329 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 14:55:00,329 - SeaingAPIClient - INFO - /config - 200
2024-11-07 14:55:01,525 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:55:01,526 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:55:01,526 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:55:01,537 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:55:03,582 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:55:03,582 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:55:03,582 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:55:07,420 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:55:09,468 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:55:09,469 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:55:09,469 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:55:09,473 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:55:11,529 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:55:11,529 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:55:11,529 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 14:55:11,534 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 14:55:13,587 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 14:55:13,587 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 14:55:13,587 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:34:42,713 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaingclearly\\iot\\processing.py', reloading
2024-11-07 15:50:04,896 - SeaingService - ERROR - WebSocket error: [WinError 10054] An existing connection was forcibly closed by the remote host
2024-11-07 15:50:04,896 - websocket - ERROR - [WinError 10054] An existing connection was forcibly closed by the remote host - goodbye
2024-11-07 15:50:04,896 - SeaingService - INFO - WebSocket connection closed
2024-11-07 15:50:46,390 - SeaingService - INFO - Starting Seaing Service
2024-11-07 15:50:46,390 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 15:50:46,394 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 15:50:46,396 - reloader - INFO -  * Detected change in 'C:\\Users\\JosephThurlow\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\encodings\\idna.py', reloading
2024-11-07 15:50:48,222 - SeaingService - INFO - Starting Seaing Service
2024-11-07 15:50:48,222 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-07 15:50:48,225 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-07 15:50:50,270 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /auth-challenge HTTP/11" 200 54
2024-11-07 15:50:50,271 - SeaingAPIClient - INFO - /auth-challenge - 200
2024-11-07 15:50:50,271 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:50:52,311 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /authenticate HTTP/11" 200 45
2024-11-07 15:50:52,312 - SeaingAPIClient - INFO - /authenticate - 200
2024-11-07 15:50:52,313 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:50:54,352 - websocket - INFO - Websocket connected
2024-11-07 15:50:54,352 - SeaingService - INFO - WebSocket connection opened
2024-11-07 15:50:54,357 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 1167
2024-11-07 15:50:54,358 - SeaingAPIClient - INFO - /options - 200
2024-11-07 15:50:54,381 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:50:56,444 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 15:50:56,445 - SeaingAPIClient - INFO - /config - 200
2024-11-07 15:51:47,153 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:51:49,204 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:51:49,204 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:51:49,204 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:00,140 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:02,192 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:02,193 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:02,193 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:02,199 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:04,250 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:04,251 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:04,251 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:06,761 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:07,478 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): localhost:5000
2024-11-07 15:52:08,810 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 15:52:08,811 - SeaingAPIClient - INFO - /config - 200
2024-11-07 15:52:09,528 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:09,528 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:09,528 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:10,217 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:12,253 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:12,253 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:12,253 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:23,512 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:25,580 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:25,580 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:25,580 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:26,008 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:28,031 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:28,032 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:28,032 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:28,825 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:30,859 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:30,859 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:30,859 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:31,187 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:33,218 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:33,218 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:33,218 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:52:41,778 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:52:43,814 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:52:43,814 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:52:43,814 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:04,018 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:06,056 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:06,056 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:06,056 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:06,067 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:08,128 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:08,128 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:08,128 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:20,037 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:20,508 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:22,080 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 15:53:22,081 - SeaingAPIClient - INFO - /config - 200
2024-11-07 15:53:22,550 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 15:53:22,550 - SeaingAPIClient - INFO - /config - 200
2024-11-07 15:53:24,952 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:26,993 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:26,994 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:26,994 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:28,032 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:30,062 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:30,063 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:30,063 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:30,424 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:32,469 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:32,470 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:32,470 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:40,688 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:42,731 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:42,731 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:42,731 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:42,807 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:44,844 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:44,845 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:44,845 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-07 15:53:45,898 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:47,957 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-07 15:53:47,958 - SeaingAPIClient - INFO - /config - 200
2024-11-07 15:53:48,910 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-07 15:53:50,970 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-07 15:53:50,971 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-07 15:53:50,971 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 97, in enhanceImage
    self.client.upload(img_bytes, self.session_id)
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 81, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-14 19:27:35,932 - SeaingService - INFO - Starting Seaing Service
2024-11-14 19:27:35,932 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-14 19:27:35,944 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
