2024-11-05 08:12:19,996 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:12:19,996 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:12:19,998 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:12:22,041 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:12:22,041 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:12:22,062 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:12:24,101 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:12:24,102 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:14:38,587 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:14:40,644 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:14:40,644 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:14:40,644 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:15:05,841 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\venv\\Lib\\site-packages\\pyotp\\__init__.py', reloading
2024-11-05 08:19:39,021 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:19:39,021 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:19:39,024 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:19:41,050 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:19:41,050 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:19:41,070 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:19:43,115 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:19:43,115 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:19:45,613 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:19:47,665 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:19:47,666 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:19:47,666 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:20:01,296 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:03,343 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:20:03,344 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:20:03,351 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:05,433 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:20:05,434 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:20:05,440 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:07,624 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:20:07,626 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:20:07,637 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:09,920 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:20:09,920 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:20:12,411 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:15,053 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:20:15,054 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:20:52,356 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:20:54,742 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:20:54,744 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:20:54,744 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:21:08,424 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:21:10,794 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:21:10,795 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:21:10,796 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:21:56,692 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:21:56,693 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:21:56,693 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:24:20,236 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:24:20,236 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:24:20,238 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:24:22,264 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:24:22,264 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:24:22,284 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:24:24,327 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:24:24,328 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:24:25,481 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:24:27,534 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:24:27,535 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:24:27,535 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:25:11,934 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:25:13,980 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:25:13,980 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:25:13,983 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:25:16,038 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:25:16,038 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:25:17,876 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:25:19,923 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:25:19,924 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:25:21,219 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:25:23,267 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:25:23,267 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:25:23,267 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:26:07,017 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:26:07,017 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:26:07,018 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:26:12,383 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:26:12,384 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:26:12,386 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:26:14,442 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:26:14,443 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:26:14,460 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:26:16,506 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:26:16,507 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:26:23,931 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:26:25,992 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:26:25,992 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:26:25,995 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:26:28,038 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:26:28,038 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:26:28,042 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:26:30,069 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:26:30,069 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:26:31,926 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:26:33,969 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:26:33,970 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:26:33,970 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:27:05,969 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:27:05,970 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:27:05,970 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:27:14,618 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:27:14,619 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:27:14,621 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:27:16,671 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:27:16,671 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:27:16,689 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:27:18,714 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:27:18,714 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:27:21,617 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:27:23,661 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:27:23,662 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:27:23,665 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:27:25,704 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:27:25,705 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:27:26,376 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:27:28,404 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:27:28,405 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:27:31,243 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:27:33,301 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:27:33,301 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:27:33,301 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:28:08,222 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:28:08,222 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:28:08,223 - reloader - INFO -  * Detected change in 'D:\\Programming\\_UNI\\seaingclearly\\seaserver\\app.py', reloading
2024-11-05 08:28:17,846 - SeaingService - INFO - Starting Seaing Service
2024-11-05 08:28:17,846 - SeaingService - INFO - Device: {"device_name": "joetdev", "ip_address": "192.168.1.116", "os_info": "Windows", "machine_info": "AMD64", "mac_address": "00:d8:61:a9:cb:64", "uuid": "ec1a91bb-7ff4-51c8-9c4c-90ff9d4f8af1"}
2024-11-05 08:28:17,848 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:5000
2024-11-05 08:28:19,903 - urllib3.connectionpool - DEBUG - http://localhost:5000 "GET /options HTTP/11" 200 732
2024-11-05 08:28:19,903 - SeaingAPIClient - INFO - /options - 200
2024-11-05 08:28:19,921 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:21,956 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:28:21,957 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:28:25,118 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:27,179 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:28:27,180 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:28:27,183 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:29,219 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:28:29,219 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:28:29,300 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:31,358 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /config HTTP/11" 200 37
2024-11-05 08:28:31,359 - SeaingAPIClient - INFO - /config - 200
2024-11-05 08:28:39,146 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:41,191 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:28:41,191 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:28:41,191 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
2024-11-05 08:28:44,272 - urllib3.connectionpool - DEBUG - Resetting dropped connection: localhost
2024-11-05 08:28:46,321 - urllib3.connectionpool - DEBUG - http://localhost:5000 "POST /image/enhance HTTP/11" 202 38
2024-11-05 08:28:46,322 - SeaingAPIClient - ERROR - /image/enhance - 202 - {'message': 'Processing started'}
2024-11-05 08:28:46,322 - SeaingService - ERROR - Failed to upload to /image/enhance
Traceback (most recent call last):
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\service.py", line 52, in enhanceImage
    enhanced_img_bytes = self.client.upload(img_bytes)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\_UNI\seaingclearly\seaingclearly\iot\client.py", line 78, in upload
    raise Exception(f"Failed to upload to {SeaingAPIClient.Endpoints.ENHANCE.value}")
Exception: Failed to upload to /image/enhance
